default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: zoom_development

test:
  <<: *default
  database: zoom_test

production:
  <<: *default
  database: zoom_production
  username: zoom
  password: <%= ENV['ZOOM_DATABASE_PASSWORD'] %>
